spring.application.name=MySpringApp
serv.port=8080
team.name=Awesome Team
#management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=health,info
#management.info.env.enabled=true

info.app.name=My Spring App
info.app.description=This is a sample Spring Boot application.
info.app.version=1.0.0

server.servlet.context-path=/myapp
spring.main.lazy-initialization=true

spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#Turn off Spring Boot banner
spring.main.banner-mode=off
#Reduce logging level
logging.level.root=warn

# Add logging configs to display SQL statements
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Configuration for JPA/Hibernate to auto create the database tables
# Do not use this in production.
# spring.jpa.hibernate.ddl-auto=create